import { ChildData } from '@/types';

export const DEMO_STUDENTS: ChildData[] = [
  {
    id: 'demo-child-1',
    user_id: 'demo-user-1',
    bracelet_id: 'NF-BR-1001',
    classe: 'Primary Focus',
    age: 9,
    focus_score: 83,
    weeklyProgress: [72, 74, 78, 82, 85, 84, 88],
    currentMood: 'Stable',
    milestonesReached: 4,
    sentimentTrend: 16,
    user: {
      id: 'demo-user-1',
      nom: 'Amina Okafor',
      email: 'amina.demo@synstorm.local',
      role: 'enfant',
      avatar_url: 'https://i.pravatar.cc/150?u=amina-demo',
    },
    braceletStatus: 'connected',
    braceletBattery: 92,
    locationLabel: 'Reading Corner',
    currentActivity: 'Guided reading',
    hydrationLevel: 84,
  },
  {
    id: 'demo-child-2',
    user_id: 'demo-user-2',
    bracelet_id: 'NF-BR-1002',
    classe: 'Primary Focus',
    age: 10,
    focus_score: 61,
    weeklyProgress: [68, 66, 63, 65, 60, 59, 61],
    currentMood: 'Needs Attention',
    milestonesReached: 2,
    sentimentTrend: -4,
    user: {
      id: 'demo-user-2',
      nom: 'Leo Mensah',
      email: 'leo.demo@synstorm.local',
      role: 'enfant',
      avatar_url: 'https://i.pravatar.cc/150?u=leo-demo',
    },
    braceletStatus: 'syncing',
    braceletBattery: 58,
    locationLabel: 'Science Lab',
    currentActivity: 'Math focus block',
    hydrationLevel: 61,
  },
  {
    id: 'demo-child-3',
    user_id: 'demo-user-3',
    bracelet_id: 'NF-BR-1003',
    classe: 'Emotional Skills',
    age: 8,
    focus_score: 39,
    weeklyProgress: [58, 51, 46, 42, 41, 38, 39],
    currentMood: 'Critical',
    milestonesReached: 1,
    sentimentTrend: -12,
    user: {
      id: 'demo-user-3',
      nom: 'Tobi Adewale',
      email: 'tobi.demo@synstorm.local',
      role: 'enfant',
      avatar_url: 'https://i.pravatar.cc/150?u=tobi-demo',
    },
    braceletStatus: 'low_battery',
    braceletBattery: 14,
    locationLabel: 'Sensory Room',
    currentActivity: 'Emotion regulation break',
    hydrationLevel: 49,
  },
  {
    id: 'demo-child-4',
    user_id: 'demo-user-4',
    bracelet_id: 'NF-BR-1004',
    classe: 'Creative Focus',
    age: 11,
    focus_score: 74,
    weeklyProgress: [62, 66, 70, 71, 74, 76, 79],
    currentMood: 'Stable',
    milestonesReached: 5,
    sentimentTrend: 11,
    user: {
      id: 'demo-user-4',
      nom: 'Nora Diallo',
      email: 'nora.demo@synstorm.local',
      role: 'enfant',
      avatar_url: 'https://i.pravatar.cc/150?u=nora-demo',
    },
    braceletStatus: 'connected',
    braceletBattery: 76,
    locationLabel: 'Art Studio',
    currentActivity: 'Creative writing',
    hydrationLevel: 73,
  },
];

